### ISSUE TITLE
Non-gnome apps not displaying fonts

### ISSUE THREAD

**Issue by jkmacy** [system76/pop-fonts#1]
The Window Titles font, when set to a fira sans/roboto slab font, work on applications made by GNOME, but Chrome, or Telegram, for example, show empty boxes.
What are your thoughts on any possible problems?
Thanks in advance.
![screenshot from 2017-04-26 18-18-31](https://cloud.githubusercontent.com/assets/16734358/25461150/edbe3bc6-2aac-11e7-89f0-36430ab21c68.png)

**Comment by isantop** [comment]
This seems to be a bug caused by Metacity or GNOME when the fonts are changed. Try logging out and logging back in (or rebooting the computer) to see if the issue persists.

**Comment by isantop** [comment]
Didn't mean to close prematurely, sorry about that.

**Comment by jkmacy** [comment]
And it's fixed. Thanks for the tip!
Logging out, then in, did the trick.  :+1:
