### ISSUE TITLE
Included Fira Code is incomplete and does not include ligatures

### ISSUE THREAD

**Issue by hanjiexi** [system76/pop-fonts#2]
Hello,

I prefer to install the fonts package via PPA rather than manually moving files around my system, however, the included Fira Code files are quite different from the [upstream Fira Code](https://github.com/tonsky/FiraCode), such as not including ligatures. At first I tried installing some other Fira Code fonts from upstream such as Fira Code Retina, which does work for some applications, however not all applications allow me to distinguish between Fira Code Retina and Fira Code.

So ultimately, my only choice would be to uninstall the fonts package from the PPA and manually install all the System76 fonts, and then overwrite the incomplete Fira Code files with the files from upstream Fira Code. This is a pain and I'm hoping you can either just ship the proper Fira Code files to begin with, or not at all.

**Comment by isantop** [comment]
Thanks for your message! Fira Code is actually a third-party project and separate from the standard Fira font family. I believe the version that got included in the package is from Font Squirrel, and it probably shouldn't be included. Sorry about that!
