### ISSUE TITLE
Can't add PPA under Ubuntu 17.04

### ISSUE THREAD

**Issue by Naatan** [system76/pop-fonts#3]
```
Error: 'paa:system76/pop' invalid
```

Assuming it's 17.10 only? Shame cause the downloaded debs work fine. Would love to receive updates.

**Comment by jackpot51** [comment]
You are getting in to this too early. We *just* created the PPA, and have yet to have complete builds of all the pop packages.

**Comment by Naatan** [comment]
Dumb coincidence honestly :) I just received my Galago Pro and read the article on omgubuntu.

**Comment by isantop** [comment]
Just noticed that there was also a typo in the README. It should read `ppa:` not `paa:`. This is also now fixed.
